spring:
  application:
    name: ${SERVER_NAME}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: ${JPA_SHOW_FORMAT_SQL}
        default_schema: storedb
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: update
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}